# Copyright (c) 2025-2026 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//build/ohos.gni")
import("//build/test.gni")
import("//foundation/communication/netstack/netstack_config.gni")

SOCKET_NATIVE = "$NETSTACK_NATIVE_ROOT/socket_native"
TLS = "$NETSTACK_NATIVE_ROOT/tls_socket"
PROXY = "$NETSTACK_NATIVE_ROOT/proxy"

ohos_unittest("socket_native_unittest") {
  module_out_path = "netstack/netstack/socket_native_unittest"

  include_dirs = [
    "$NETSTACK_DIR/utils/common_utils/include",
    "$NETSTACK_DIR/utils/log/include",
    "$TLS/include",
    "$PROXY/include",
    "$NETSTACK_INNERKITS_DIR/socket_native/include",
    "$SOCKET_NATIVE/constant/include",
    "$SOCKET_NATIVE/options/include",
    "$SOCKET_NATIVE/socket_exec/include",
  ]

  sources = [
    # Socket exec sources
    "$SOCKET_NATIVE/socket_exec/src/tcp_socket_server.cpp",
    "$SOCKET_NATIVE/socket_exec/src/tcp_socket_client.cpp",
    "$SOCKET_NATIVE/socket_exec/src/socket_exec_common.cpp",
    "$SOCKET_NATIVE//socket_exec/src/socket_exec_error.cpp",
    "$SOCKET_NATIVE/socket_exec/src/connect_monitor.cpp",
    "$SOCKET_NATIVE/socket_exec/src/udp_socket.cpp",
    "$SOCKET_NATIVE/socket_exec/src/local_socket_client.cpp",
    "$SOCKET_NATIVE/socket_exec/src/local_socket_server.cpp",
    "$SOCKET_NATIVE/socket_exec/src/tls_socket_client.cpp",
    "$SOCKET_NATIVE/socket_exec/src/tls_socket_server.cpp",

    # Options data models
    "$SOCKET_NATIVE/options/src/extra_options_base.cpp",
    "$SOCKET_NATIVE/options/src/local_socket_options.cpp",
    "$SOCKET_NATIVE/options/src/net_address.cpp",
    "$SOCKET_NATIVE/options/src/socket_remote_info.cpp",
    "$SOCKET_NATIVE/options/src/socket_state_base.cpp",
    "$SOCKET_NATIVE/options/src/tcp_connect_options.cpp",
    "$SOCKET_NATIVE/options/src/tcp_extra_options.cpp",
    "$SOCKET_NATIVE/options/src/tcp_send_options.cpp",
    "$SOCKET_NATIVE/options/src/udp_extra_options.cpp",
    "$SOCKET_NATIVE/options/src/udp_send_options.cpp",

    # TLS sources
    "$TLS/src/secure_data.cpp",
    "$TLS/src/socket_error.cpp",
    "$TLS/src/tls_certificate.cpp",
    "$TLS/src/tls_config_enhanced.cpp",
    "$TLS/src/tls_configuration.cpp",
    "$TLS/src/tls_context.cpp",
    "$TLS/src/tls_context_server.cpp",
    "$TLS/src/tls_key.cpp",
    "$TLS/src/tls_utils.cpp",

    # Proxy sources
    "$PROXY/src/socks5_instance.cpp",
    "$PROXY/src/socks5_none_method.cpp",
    "$PROXY/src/socks5_package.cpp",
    "$PROXY/src/socks5_passwd_method.cpp",
    "$PROXY/src/socks5_utils.cpp",

    "$NETSTACK_DIR/utils/common_utils/src/netstack_common_utils.cpp",

    # Test sources
    "TcpSocketClientTest.cpp",
    "TcpSocketServerTest.cpp",
    "UdpSocketTest.cpp",
    "LocalSocketClientTest.cpp",
    "LocalSocketServerTest.cpp",
    "tls_socket_client_test.cpp",
    "socks5_test.cpp",
    "secure_data_test.cpp",
    "tls_connect_options_test.cpp",
    "tls_secure_options_test.cpp",
    "tls_socket_error_test.cpp",
    "ConnectMonitorTest.cpp",
    "TlsSocketServerTest.cpp",
  ]

  deps = [ "$NETSTACK_DIR/utils:stack_utils_common" ]

  external_deps = [
    "c_utils:utils",
    "bounds_checking_function:libsec_shared",
    "hilog:libhilog",
    "openssl:libcrypto_shared",
    "openssl:libssl_shared",
  ]

  defines = [
    "NETMGR_LOG_TAG = \"SocketNativeUT\"",
    "LOG_DOMAIN = 0xD0015B0",
    "OPENSSL_SUPPRESS_DEPRECATED",
  ]

  if (defined(global_parts_info) &&
      defined(global_parts_info.communication_netmanager_base) &&
      global_parts_info.communication_netmanager_base) {
    external_deps += [
      "netmanager_base:net_conn_manager_if",
      "netmanager_base:net_security_config_if",
    ]
    defines += [ "HAS_NETMANAGER_BASE=1" ]
  } else {
    defines += [ "HAS_NETMANAGER_BASE=0" ]
  }

  part_name = "netstack"
  subsystem_name = "communication"
}

group("unittest") {
  testonly = true
  deps = [ ":socket_native_unittest" ]
}
